
title: My Resume
url: 'http://www.albertobaselga.com'
baseurl: 'www.albertobaselga.com' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-6
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Alberto Baselga
tagline: DevOps
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: alberto.baselga@gmail.com
phone: 699 697 868
website: albertobaselga.com #do not add http://
linkedin: albertobaselga
github: albertobaselga
twitter: ''


# Tracker
analytics: UA-101130659-1
#Update all the sections by editing the files inside _includes folder.
